version: "2"

run:
  concurrency: 4
  timeout: 15m
  tests: true

linters:
  fast: false
  # v2 uses `default`, so set to none to mirror v1's disable-all=true.
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
  settings:
    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Default is to use a neutral variety of English.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      locale: US
    custom:
      # ref. https://github.com/uber-go/nilaway
      nilaway:
        type: "module"
        description: Static analysis tool to detect potential nil panics in Go code.
        settings:
          include-pkgs: "github.com/leptonai/gpud"
          exclude-pkgs: "github.com/leptonai/gpud/pkg/third_party"
          experimental-anonymous-function: "true"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      # put imports beginning with prefix after 3rd-party packages;
      # it's a comma-separated list of prefixes
      local-prefixes: lepton.ai/lepton
