// Copyright (c) 2026, Lepton AI. All rights reserved.
//
// This is a minimal, wire-compatible subset of NVSentinel's
// data-models/protobufs/health_event.proto (package "datamodels").
// Only the messages and fields that GPUd consumes are declared here.
// Field numbers match upstream, so events sent by NVSentinel
// platform-connectors decode correctly; fields GPUd does not need
// (BehaviourOverrides, CRD wrappers) are reserved and skipped on the wire.
//
// Upstream: github.com/NVIDIA/NVSentinel (Apache License 2.0).
//
// Regenerate with: go generate ./pkg/nvsentinel/...

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: health_event.proto

package datamodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecommendedAction mirrors the upstream enum. Values are sparse upstream;
// the numbering must stay identical for wire compatibility.
type RecommendedAction int32

const (
	RecommendedAction_NONE            RecommendedAction = 0
	RecommendedAction_COMPONENT_RESET RecommendedAction = 2
	RecommendedAction_CONTACT_SUPPORT RecommendedAction = 5
	RecommendedAction_RUN_FIELDDIAG   RecommendedAction = 6
	RecommendedAction_RESTART_VM      RecommendedAction = 15
	RecommendedAction_RESTART_BM      RecommendedAction = 24
	RecommendedAction_REPLACE_VM      RecommendedAction = 25
	RecommendedAction_RUN_DCGMEUD     RecommendedAction = 26
	RecommendedAction_CUSTOM          RecommendedAction = 27
	RecommendedAction_UNKNOWN         RecommendedAction = 99
)

// Enum value maps for RecommendedAction.
var (
	RecommendedAction_name = map[int32]string{
		0:  "NONE",
		2:  "COMPONENT_RESET",
		5:  "CONTACT_SUPPORT",
		6:  "RUN_FIELDDIAG",
		15: "RESTART_VM",
		24: "RESTART_BM",
		25: "REPLACE_VM",
		26: "RUN_DCGMEUD",
		27: "CUSTOM",
		99: "UNKNOWN",
	}
	RecommendedAction_value = map[string]int32{
		"NONE":            0,
		"COMPONENT_RESET": 2,
		"CONTACT_SUPPORT": 5,
		"RUN_FIELDDIAG":   6,
		"RESTART_VM":      15,
		"RESTART_BM":      24,
		"REPLACE_VM":      25,
		"RUN_DCGMEUD":     26,
		"CUSTOM":          27,
		"UNKNOWN":         99,
	}
)

func (x RecommendedAction) Enum() *RecommendedAction {
	p := new(RecommendedAction)
	*p = x
	return p
}

func (x RecommendedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_health_event_proto_enumTypes[0].Descriptor()
}

func (RecommendedAction) Type() protoreflect.EnumType {
	return &file_health_event_proto_enumTypes[0]
}

func (x RecommendedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendedAction.Descriptor instead.
func (RecommendedAction) EnumDescriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{0}
}

// ProcessingStrategy tells downstream NVSentinel modules how to handle the
// event. GPUd only observes events, so this is informational here.
type ProcessingStrategy int32

const (
	ProcessingStrategy_UNSPECIFIED         ProcessingStrategy = 0
	ProcessingStrategy_EXECUTE_REMEDIATION ProcessingStrategy = 1
	ProcessingStrategy_STORE_ONLY          ProcessingStrategy = 2
	ProcessingStrategy_STORE_AND_ANALYSE   ProcessingStrategy = 3
)

// Enum value maps for ProcessingStrategy.
var (
	ProcessingStrategy_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "EXECUTE_REMEDIATION",
		2: "STORE_ONLY",
		3: "STORE_AND_ANALYSE",
	}
	ProcessingStrategy_value = map[string]int32{
		"UNSPECIFIED":         0,
		"EXECUTE_REMEDIATION": 1,
		"STORE_ONLY":          2,
		"STORE_AND_ANALYSE":   3,
	}
)

func (x ProcessingStrategy) Enum() *ProcessingStrategy {
	p := new(ProcessingStrategy)
	*p = x
	return p
}

func (x ProcessingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_health_event_proto_enumTypes[1].Descriptor()
}

func (ProcessingStrategy) Type() protoreflect.EnumType {
	return &file_health_event_proto_enumTypes[1]
}

func (x ProcessingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStrategy.Descriptor instead.
func (ProcessingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{1}
}

type HealthEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Events        []*HealthEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthEvents) Reset() {
	*x = HealthEvents{}
	mi := &file_health_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvents) ProtoMessage() {}

func (x *HealthEvents) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvents.ProtoReflect.Descriptor instead.
func (*HealthEvents) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{0}
}

func (x *HealthEvents) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvents) GetEvents() []*HealthEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityValue   string                 `protobuf:"bytes,2,opt,name=entityValue,proto3" json:"entityValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_health_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Entity) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

type HealthEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Version                 uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Agent                   string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	ComponentClass          string                 `protobuf:"bytes,3,opt,name=componentClass,proto3" json:"componentClass,omitempty"`
	CheckName               string                 `protobuf:"bytes,4,opt,name=checkName,proto3" json:"checkName,omitempty"`
	IsFatal                 bool                   `protobuf:"varint,5,opt,name=isFatal,proto3" json:"isFatal,omitempty"`
	IsHealthy               bool                   `protobuf:"varint,6,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	Message                 string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	RecommendedAction       RecommendedAction      `protobuf:"varint,8,opt,name=recommendedAction,proto3,enum=datamodels.RecommendedAction" json:"recommendedAction,omitempty"`
	ErrorCode               []string               `protobuf:"bytes,9,rep,name=errorCode,proto3" json:"errorCode,omitempty"`
	EntitiesImpacted        []*Entity              `protobuf:"bytes,10,rep,name=entitiesImpacted,proto3" json:"entitiesImpacted,omitempty"`
	Metadata                map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GeneratedTimestamp      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=generatedTimestamp,proto3" json:"generatedTimestamp,omitempty"`
	NodeName                string                 `protobuf:"bytes,13,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	ProcessingStrategy      ProcessingStrategy     `protobuf:"varint,16,opt,name=processingStrategy,proto3,enum=datamodels.ProcessingStrategy" json:"processingStrategy,omitempty"`
	Id                      string                 `protobuf:"bytes,17,opt,name=id,proto3" json:"id,omitempty"`
	CustomRecommendedAction string                 `protobuf:"bytes,18,opt,name=customRecommendedAction,proto3" json:"customRecommendedAction,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_health_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{2}
}

func (x *HealthEvent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvent) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *HealthEvent) GetComponentClass() string {
	if x != nil {
		return x.ComponentClass
	}
	return ""
}

func (x *HealthEvent) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *HealthEvent) GetIsFatal() bool {
	if x != nil {
		return x.IsFatal
	}
	return false
}

func (x *HealthEvent) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthEvent) GetRecommendedAction() RecommendedAction {
	if x != nil {
		return x.RecommendedAction
	}
	return RecommendedAction_NONE
}

func (x *HealthEvent) GetErrorCode() []string {
	if x != nil {
		return x.ErrorCode
	}
	return nil
}

func (x *HealthEvent) GetEntitiesImpacted() []*Entity {
	if x != nil {
		return x.EntitiesImpacted
	}
	return nil
}

func (x *HealthEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HealthEvent) GetGeneratedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedTimestamp
	}
	return nil
}

func (x *HealthEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HealthEvent) GetProcessingStrategy() ProcessingStrategy {
	if x != nil {
		return x.ProcessingStrategy
	}
	return ProcessingStrategy_UNSPECIFIED
}

func (x *HealthEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthEvent) GetCustomRecommendedAction() string {
	if x != nil {
		return x.CustomRecommendedAction
	}
	return ""
}

var File_health_event_proto protoreflect.FileDescriptor

const file_health_event_proto_rawDesc = "" +
	"\n" +
	"\x12health_event.proto\x12\n" +
	"datamodels\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\fHealthEvents\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12/\n" +
	"\x06events\x18\x02 \x03(\v2\x17.datamodels.HealthEventR\x06events\"J\n" +
	"\x06Entity\x12\x1e\n" +
	"\n" +
	"entityType\x18\x01 \x01(\tR\n" +
	"entityType\x12 \n" +
	"\ventityValue\x18\x02 \x01(\tR\ventityValue\"\x8e\x06\n" +
	"\vHealthEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12&\n" +
	"\x0ecomponentClass\x18\x03 \x01(\tR\x0ecomponentClass\x12\x1c\n" +
	"\tcheckName\x18\x04 \x01(\tR\tcheckName\x12\x18\n" +
	"\aisFatal\x18\x05 \x01(\bR\aisFatal\x12\x1c\n" +
	"\tisHealthy\x18\x06 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12K\n" +
	"\x11recommendedAction\x18\b \x01(\x0e2\x1d.datamodels.RecommendedActionR\x11recommendedAction\x12\x1c\n" +
	"\terrorCode\x18\t \x03(\tR\terrorCode\x12>\n" +
	"\x10entitiesImpacted\x18\n" +
	" \x03(\v2\x12.datamodels.EntityR\x10entitiesImpacted\x12A\n" +
	"\bmetadata\x18\v \x03(\v2%.datamodels.HealthEvent.MetadataEntryR\bmetadata\x12J\n" +
	"\x12generatedTimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x12generatedTimestamp\x12\x1a\n" +
	"\bnodeName\x18\r \x01(\tR\bnodeName\x12N\n" +
	"\x12processingStrategy\x18\x10 \x01(\x0e2\x1e.datamodels.ProcessingStrategyR\x12processingStrategy\x12\x0e\n" +
	"\x02id\x18\x11 \x01(\tR\x02id\x128\n" +
	"\x17customRecommendedAction\x18\x12 \x01(\tR\x17customRecommendedAction\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10*\xb4\x01\n" +
	"\x11RecommendedAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\x13\n" +
	"\x0fCOMPONENT_RESET\x10\x02\x12\x13\n" +
	"\x0fCONTACT_SUPPORT\x10\x05\x12\x11\n" +
	"\rRUN_FIELDDIAG\x10\x06\x12\x0e\n" +
	"\n" +
	"RESTART_VM\x10\x0f\x12\x0e\n" +
	"\n" +
	"RESTART_BM\x10\x18\x12\x0e\n" +
	"\n" +
	"REPLACE_VM\x10\x19\x12\x0f\n" +
	"\vRUN_DCGMEUD\x10\x1a\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x1b\x12\v\n" +
	"\aUNKNOWN\x10c*e\n" +
	"\x12ProcessingStrategy\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXECUTE_REMEDIATION\x10\x01\x12\x0e\n" +
	"\n" +
	"STORE_ONLY\x10\x02\x12\x15\n" +
	"\x11STORE_AND_ANALYSE\x10\x032`\n" +
	"\x11PlatformConnector\x12K\n" +
	"\x15HealthEventOccurredV1\x12\x18.datamodels.HealthEvents\x1a\x16.google.protobuf.Empty\"\x00B:Z8github.com/leptonai/gpud/pkg/nvsentinel/proto/datamodelsb\x06proto3"

var (
	file_health_event_proto_rawDescOnce sync.Once
	file_health_event_proto_rawDescData []byte
)

func file_health_event_proto_rawDescGZIP() []byte {
	file_health_event_proto_rawDescOnce.Do(func() {
		file_health_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_event_proto_rawDesc), len(file_health_event_proto_rawDesc)))
	})
	return file_health_event_proto_rawDescData
}

var file_health_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_health_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_health_event_proto_goTypes = []any{
	(RecommendedAction)(0),        // 0: datamodels.RecommendedAction
	(ProcessingStrategy)(0),       // 1: datamodels.ProcessingStrategy
	(*HealthEvents)(nil),          // 2: datamodels.HealthEvents
	(*Entity)(nil),                // 3: datamodels.Entity
	(*HealthEvent)(nil),           // 4: datamodels.HealthEvent
	nil,                           // 5: datamodels.HealthEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_health_event_proto_depIdxs = []int32{
	4, // 0: datamodels.HealthEvents.events:type_name -> datamodels.HealthEvent
	0, // 1: datamodels.HealthEvent.recommendedAction:type_name -> datamodels.RecommendedAction
	3, // 2: datamodels.HealthEvent.entitiesImpacted:type_name -> datamodels.Entity
	5, // 3: datamodels.HealthEvent.metadata:type_name -> datamodels.HealthEvent.MetadataEntry
	6, // 4: datamodels.HealthEvent.generatedTimestamp:type_name -> google.protobuf.Timestamp
	1, // 5: datamodels.HealthEvent.processingStrategy:type_name -> datamodels.ProcessingStrategy
	2, // 6: datamodels.PlatformConnector.HealthEventOccurredV1:input_type -> datamodels.HealthEvents
	7, // 7: datamodels.PlatformConnector.HealthEventOccurredV1:output_type -> google.protobuf.Empty
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_health_event_proto_init() }
func file_health_event_proto_init() {
	if File_health_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_event_proto_rawDesc), len(file_health_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_event_proto_goTypes,
		DependencyIndexes: file_health_event_proto_depIdxs,
		EnumInfos:         file_health_event_proto_enumTypes,
		MessageInfos:      file_health_event_proto_msgTypes,
	}.Build()
	File_health_event_proto = out.File
	file_health_event_proto_goTypes = nil
	file_health_event_proto_depIdxs = nil
}
