package v1

// LoginRequest is the request for the login request.
type LoginRequest struct {
	Token              string            `json:"token"`
	MachineID          string            `json:"machineID"`
	NodeGroup          string            `json:"nodeGroup,omitempty"`
	Network            *MachineNetwork   `json:"network,omitempty"`
	Location           *MachineLocation  `json:"location,omitempty"`
	Provider           string            `json:"provider"`
	ProviderInstanceID string            `json:"providerInstanceID"`
	MachineInfo        *MachineInfo      `json:"machineInfo,omitempty"`
	Resources          map[string]string `json:"resources,omitempty"`
}

// LoginResponse is the response for the login request.
type LoginResponse struct {
	// Code is internal status code
	Code string `json:"code,omitempty"`

	// Message is the error message for the login request
	Message string `json:"message,omitempty"`

	// Deprecated: use Code instead of it
	// Status is the status of the login request.
	Status string `json:"status,omitempty"`

	// Deprecated: use Message instead of it
	// Error is the error message for the login request.
	// The error is only returned if the machine ID retrieval fails.
	Error string `json:"error,omitempty"`

	// MachineID is the ID of the machine generated by the login control plane.
	// Only set upon successful login.
	MachineID string `json:"machineID"`

	// Token is the token used to report data from the machine.
	Token string `json:"token,omitempty"`

	// ValidationResults is the validation results for the login request.
	// The validation results are done by the control plane.
	ValidationResults []ValidationResult `json:"validationResults,omitempty"`
}

// ValidationResult is the validation result for the login request.
type ValidationResult struct {
	Name       string `json:"name"`
	Valid      bool   `json:"valid"`
	Reason     string `json:"reason"`
	Suggestion string `json:"suggestion"`
}
