package v1

// LoginRequest is the request for the login request.
type LoginRequest struct {
	Token              string            `json:"token"`
	MachineID          string            `json:"machineID"`
	Network            *MachineNetwork   `json:"network,omitempty"`
	Location           *MachineLocation  `json:"location,omitempty"`
	Provider           string            `json:"provider"`
	ProviderInstanceID string            `json:"providerInstanceID"`
	MachineInfo        *MachineInfo      `json:"machineInfo,omitempty"`
	Resources          map[string]string `json:"resources,omitempty"`
}

// LoginResponse is the response for the login request.
type LoginResponse struct {
	// Status is the status of the login request.
	Status string `json:"status,omitempty"`

	// Error is the error message for the login request.
	// The error is only returned if the machine ID retrieval fails.
	Error string `json:"error,omitempty"`

	// MachineID is the ID of the machine generated by the login control plane.
	// Only set upon successful login.
	MachineID string `json:"machineID"`

	// Token is the token used to report data from the machine.
	Token string `json:"token,omitempty"`
}
