// Package xid provides the NVIDIA XID error details.
package xid

// Defines the XID error type.
// ref. https://docs.nvidia.com/deploy/pdf/XID_Errors.pdf
// ref. https://docs.nvidia.com/deploy/xid-errors/index.html#xid-error-listing
// ref. https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#xid-messages
// ref. https://docs.nvidia.com/deploy/xid-errors/index.html
// ref. https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/src/common/sdk/nvidia/inc/nverror.h
// ref. https://github.com/NVIDIA/k8s-device-plugin/blob/v0.16.0/internal/rm/health.go#L62-L76
type Detail struct {
	ID                     int    `json:"id"`
	Name                   string `json:"name"`
	Description            string `json:"description"`
	HWError                bool   `json:"hw_error"`
	DriverError            bool   `json:"driver_error"`
	UserAppError           bool   `json:"user_app_error"`
	SystemMemoryCorruption bool   `json:"system_memory_corruption"`
	BusError               bool   `json:"bus_error"`
	ThermalIssue           bool   `json:"thermal_issue"`
	FBCorruption           bool   `json:"fb_corruption"`
}

// Returns the error if found.
// Otherwise, returns false.
func GetDetail(id int) (*Detail, bool) {
	e, ok := details[id]
	return &e, ok
}

// Copied from https://docs.nvidia.com/deploy/xid-details/index.html#xid-error-listing.
// See https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#xid-messages for more details.
var details = map[int]Detail{
	1: {
		ID:                     1,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	2: {
		ID:                     2,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	3: {
		ID:                     3,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	4: {
		ID:                     4,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "or GPU semaphore timeout (then user app error is true)",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	5: {
		ID:                     5,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	6: {
		ID:                     6,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	7: {
		ID:                     7,
		Name:                   "Invalid or corrupted push buffer address",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	8: {
		ID:                     8,
		Name:                   "GPU stopped processing",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: false,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           false,
	},
	9: {
		ID:                     9,
		Name:                   "Driver error programming GPU",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	10: {
		ID:                     10,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	11: {
		ID:                     11,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	12: {
		ID:                     12,
		Name:                   "Driver error handling GPU exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	13: {
		ID:                     13,
		Name:                   "Graphics Engine Exception",
		Description:            `Run DCGM and Field diagnostics to confirm if the issue is related to hardware. If not, debug the user application using guidance from https://docs.nvidia.com/deploy/xid-errors/index.html. If the latter, see Report a GPU Issue at https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#reporting-gpu-issue.`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           true, // ref. https://github.com/NVIDIA/k8s-device-plugin/blob/v0.16.0/internal/rm/health.go#L62-L76
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           true,
	},
	14: {
		ID:                     14,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	15: {
		ID:                     15,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	16: {
		ID:                     16,
		Name:                   "Display engine hung",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	17: {
		ID:                     17,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	18: {
		ID:                     18,
		Name:                   "Bus mastering disabled in PCI Config Space",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	19: {
		ID:                     19,
		Name:                   "Display Engine error",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	20: {
		ID:                     20,
		Name:                   "Invalid or corrupted Mpeg push buffer",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	21: {
		ID:                     21,
		Name:                   "Invalid or corrupted Motion Estimation push buffer",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	22: {
		ID:                     22,
		Name:                   "Invalid or corrupted Video Processor push buffer",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	23: {
		ID:                     23,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	24: {
		ID:                     24,
		Name:                   "GPU semaphore timeout",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           true,
	},
	25: {
		ID:                     25,
		Name:                   "Invalid or illegal push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	26: {
		ID:                     26,
		Name:                   "Framebuffer timeout",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	27: {
		ID:                     27,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	28: {
		ID:                     28,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	29: {
		ID:                     29,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	30: {
		ID:                     30,
		Name:                   "GPU semaphore access error",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	31: {
		ID:                     31,
		Name:                   "GPU memory page fault",
		Description:            `Debug the user application unless the issue is new and there have been no changes to the application but there has been changes to GPU driver or other GPU system software. If the latter, see Report a GPU Issue via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#reporting-gpu-issue.`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           true, // ref. https://github.com/NVIDIA/k8s-device-plugin/blob/v0.16.0/internal/rm/health.go#L62-L76
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	32: {
		ID:                     32,
		Name:                   "Invalid or corrupted push buffer stream",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           true,
	},
	33: {
		ID:                     33,
		Name:                   "Internal micro-controller error",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	34: {
		ID:                     34,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	35: {
		ID:                     35,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	36: {
		ID:                     36,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	37: {
		ID:                     37,
		Name:                   "Driver firmware error",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	38: {
		ID:                     38,
		Name:                   "Driver firmware error",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	39: {
		ID:                     39,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	40: {
		ID:                     40,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	41: {
		ID:                     41,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	42: {
		ID:                     42,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	43: {
		ID:                     43,
		Name:                   "GPU stopped processing",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true, // ref. https://github.com/NVIDIA/k8s-device-plugin/blob/v0.16.0/internal/rm/health.go#L62-L76
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	44: {
		ID:                     44,
		Name:                   "Graphics Engine fault during context switch",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	45: {
		ID:                     45,
		Name:                   "Preemptive cleanup, due to previous errors – Most likely to see when running multiple cuda applications and hitting a DBE.",
		Description:            "Robust Channel Preemptive Removal. No action, informative only. Indicates channels affected by another failure. On A100, this error could be seen by itself due to unexpected Fabric Manager shutdown when FM is running in the same OS environment as the GPU. Otherwise, this error is safe to ignore as an informational message.",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false, // ref. https://github.com/NVIDIA/k8s-device-plugin/blob/v0.16.0/internal/rm/health.go#L62-L76
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	46: {
		ID:                     46,
		Name:                   "GPU stopped processing",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	47: {
		ID:                     47,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	48: {
		ID:   48,
		Name: "Double Bit ECC Error",
		Description: `If Xid 48 is followed by Xid 63 or 64: Drain/cordon the node, wait for all work to complete, and reset GPU(s) reporting the XID (refer to GPU reset capabilities/limitations section below).

If Xid 48 is not followed by Xid 63 or 64: see Running Field Diagnostics to collect additional debug information, via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#running-field-diag.

See below for guidelines on when to RMA GPUs based on excessive errors.
`,
		HWError:                true,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	49: {
		ID:                     49,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	50: {
		ID:                     50,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	51: {
		ID:                     51,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	52: {
		ID:                     52,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	53: {
		ID:                     53,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	54: {
		ID:                     54,
		Name:                   "Auxiliary power is not connected to the GPU board",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	55: {
		ID:                     55,
		Name:                   "Unused",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	56: {
		ID:                     56,
		Name:                   "Display Engine error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	57: {
		ID:                     57,
		Name:                   "Error programming video memory interface",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	58: {
		ID:                     58,
		Name:                   "Unstable video memory interface detected",
		Description:            "or EDC error - clarified in printout (driver error=false)",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	59: {
		ID:                     59,
		Name:                   "Internal micro-controller error (older drivers)",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	60: {
		ID:                     60,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	61: {
		ID:                     61,
		Name:                   "Internal micro-controller breakpoint/warning (newer drivers)",
		Description:            "PMU Breakpoint. Report a GPU Issue and Reset GPU(s) reporting the XID (refer GPU reset capabilities/limitations section below).",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	62: {
		ID:                     62,
		Name:                   "Internal micro-controller halt (newer drivers)",
		Description:            "PMU Halt Error. Report a GPU Issue and Reset GPU(s) reporting the XID (refer GPU reset capabilities/limitations section below).",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           true,
		FBCorruption:           false,
	},
	63: {
		ID:   63,
		Name: "ECC page retirement or row remapping recording event",
		Description: `
Legacy GPU: ECC page retirement recording event.

If associated with XID 48, drain/cordon the node, wait for all work to complete, and reset GPU(s) reporting the XID (refer GPU reset capabilities/limitations section below).

If not, it is from a single bit error and the system can keep running as is until there is a convenient time to reboot it.

See below for guidelines on when to RMA GPUs based on excessive errors.

A100: Row-remapping recording event.

If associated with XID 94, the application that encountered the error needs to be restarted. All other applications on the system can keep running as is until there is a convenient time to reset the GPU(refer GPU reset capabilities/limitations section below) or reboot for row remapping to activate.

See below for guidelines on when to RMA GPUs based on row remapping failures.

`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	64: {
		ID:   64,
		Name: "ECC page retirement or row remapper recording failure",
		Description: `
Legacy GPU: ECC page retirement recording failure.

See above, however the node should be monitored closely. If there is no associated XID 48 error, then these are related to single bit-errors. The GPU(s) reporting the error must be reset (refer to GPU reset capabilities/limitations section below) immediately since there is a recording failure. If the errors continue, drain, triage, and see Report a GPU Issue.

See below for guidelines on when to RMA GPUs based on excessive errors, via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#reporting-gpu-issue.

A100: Row-remapping recording failure.

The node should be rebooted immediately since there is a recording failure. If the errors continue, drain, triage, and see Report a GPU Issue, via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#reporting-gpu-issue.

See below for guidelines on when to RMA GPUs based on row remapping failures.

`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	65: {
		ID:                     65,
		Name:                   "Video processor exception",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	66: {
		ID:                     66,
		Name:                   "Illegal access by driver",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	67: {
		ID:                     67,
		Name:                   "Illegal access by driver",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	68: {
		ID:                     68,
		Name:                   "NVDEC0 Exception",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	69: {
		ID:                     69,
		Name:                   "Graphics Engine class error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	70: {
		ID:                     70,
		Name:                   "CE3: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	71: {
		ID:                     71,
		Name:                   "CE4: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	72: {
		ID:                     72,
		Name:                   "CE5: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	73: {
		ID:                     73,
		Name:                   "NVENC2 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	74: {
		ID:   74,
		Name: "NVLINK Error",
		Description: `
Extract the hex strings from the XID error message. eg: (0x12345678, 0x12345678, 0x12345678, 0x12345678, 0x12345678, 0x12345678, 0x12345678) Look at the bolded DWORD (the first) and take the following paths if the particular bits (counting from LSB side) are set.

Bits 4 or 5: Likely HW issue with ECC/Parity --> If seen more than 2 times on the same link, report a bug.

Bits 21 or 22: Marginal channel SI issue. Check link mechanical connecetions. If other errors accompany, follow the resolution for those.

Bits 8, 9, 12, 16, 17, 24, 28: Could possibly be a HW issue: Check link mechanical connecetions and re-seat if a field resolution is required. Run diags if issue persists.
`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	75: {
		ID:                     75,
		Name:                   "CE6: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	76: {
		ID:                     76,
		Name:                   "CE7: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	77: {
		ID:                     77,
		Name:                   "CE8: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	78: {
		ID:                     78,
		Name:                   "vGPU Start Error",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	79: {
		ID:   79,
		Name: "GPU has fallen off the bus",
		Description: `
Drain and see Report a GPU Issue, via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#reporting-gpu-issue.
`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           false,
	},
	80: {
		ID:                     80,
		Name:                   "Corrupted data sent to GPU",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	81: {
		ID:                     81,
		Name:                   "VGA Subsystem Error",
		Description:            "",
		HWError:                true,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	82: {
		ID:                     82,
		Name:                   "NVJPG0 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	83: {
		ID:                     83,
		Name:                   "NVDEC1 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	84: {
		ID:                     84,
		Name:                   "NVDEC2 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	85: {
		ID:                     85,
		Name:                   "CE9: Unknown Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	86: {
		ID:                     86,
		Name:                   "OFA Exception",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	87: {
		ID:                     87,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	88: {
		ID:                     88,
		Name:                   "NVDEC3 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	89: {
		ID:                     89,
		Name:                   "NVDEC4 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	90: {
		ID:                     90,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	91: {
		ID:                     91,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	92: {
		ID:   92,
		Name: "High single-bit ECC error rate",
		Description: `
See Running Field Diagnostics to collect additional debug information, via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#running-field-diag.

See below for guidelines on when to RMA GPUs based on excessive errors.
`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	93: {
		ID:                     93,
		Name:                   "Non-fatal violation of provisioned InfoROM wear limit",
		Description:            "",
		HWError:                false,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	94: {
		ID:   94,
		Name: "Contained ECC error",
		Description: `
(A100 only)

The application that encountered the error needs to be restarted. All other applications on the system can keep running as is until there is a convenient time to reset the GPU (refer to GPU reset capabilities/limitations section below) or reboot for row remapping to activate.

See below for guidelines on when to RMA GPUs based on row remapping failures
`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	95: {
		ID:   95,
		Name: "Uncontained ECC error",
		Description: `
(A100 only)

If MIG is enabled, drain any work on the other GPU instances, wait for all work to complete, and reset GPU(s) reporting the XID (refer to the GPU reset capabilities/limitations section below).

If MIG is disabled, the node should be rebooted immediately since there is an uncorrectable uncontained ECC error. If the errors continue, drain, triage, and see Report a GPU Issue, via https://docs.nvidia.com/deploy/gpu-debug-guidelines/index.html#reporting-gpu-issue.

See below for guidelines on when to RMA GPUs based on row remapping failures.
`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	96: {
		ID:                     96,
		Name:                   "NVDEC5 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	97: {
		ID:                     97,
		Name:                   "NVDEC6 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	98: {
		ID:                     98,
		Name:                   "NVDEC7 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	99: {
		ID:                     99,
		Name:                   "NVJPG1 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	100: {
		ID:                     100,
		Name:                   "NVJPG2 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	101: {
		ID:                     101,
		Name:                   "NVJPG3 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	102: {
		ID:                     102,
		Name:                   "NVJPG4 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	103: {
		ID:                     103,
		Name:                   "NVJPG5 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	104: {
		ID:                     104,
		Name:                   "NVJPG6 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	105: {
		ID:                     105,
		Name:                   "NVJPG7 Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	106: {
		ID:                     106,
		Name:                   "SMBPBI Test Message",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           true,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	107: {
		ID:                     107,
		Name:                   "SMBPBI Test Message Silent",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           true,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	108: {
		ID:                     108,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	109: {
		ID:                     109,
		Name:                   "Context Switch Timeout Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           true,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           true,
	},
	110: {
		ID:                     110,
		Name:                   "Security Fault Error",
		Description:            "",
		HWError:                true,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	111: {
		ID:                     111,
		Name:                   "Display Bundle Error Event",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	112: {
		ID:                     112,
		Name:                   "Display Supervisor Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	113: {
		ID:                     113,
		Name:                   "DP Link Training Erro",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	114: {
		ID:                     114,
		Name:                   "Display Pipeline Underflow Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	115: {
		ID:                     115,
		Name:                   "Display Core Channel Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	116: {
		ID:                     116,
		Name:                   "Display Window Channel Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	117: {
		ID:                     117,
		Name:                   "Display Cursor Channel Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	118: {
		ID:                     118,
		Name:                   "Display Pixel Pipeline Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	119: {
		ID:                     119,
		Name:                   "GSP RPC Timeout",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           true,
	},
	120: {
		ID:                     120,
		Name:                   "GSP Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: true,
		BusError:               true,
		ThermalIssue:           true,
		FBCorruption:           true,
	},
	121: {
		ID:                     121,
		Name:                   "C2C Link Error",
		Description:            "",
		HWError:                true,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               true,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	122: {
		ID:                     122,
		Name:                   "SPI PMU RPC Read Failure",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	123: {
		ID:   123,
		Name: "SPI PMU RPC Write Failure",
		Description: `
Report a GPU issue and reset GPU(s) reporting the XID (refer to GPU reset capabilities/limitations section provided in Section D.9 of the FM User Guide: https://docs.nvidia.com/datacenter/tesla/pdf/fabric-manager-user-guide.pdf).
`,
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	124: {
		ID:                     124,
		Name:                   "SPI PMU RPC Erase Failure",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	125: {
		ID:                     125,
		Name:                   "Inforom FS Failure",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	126: {
		ID:                     126,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	127: {
		ID:                     127,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	128: {
		ID:                     128,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	129: {
		ID:                     129,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	130: {
		ID:                     130,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	131: {
		ID:                     131,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	132: {
		ID:                     132,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	134: {
		ID:                     134,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	135: {
		ID:                     135,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	136: {
		ID:                     136,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	137: {
		ID:                     137,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	138: {
		ID:                     138,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	139: {
		ID:                     139,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	140: {
		ID:                     140,
		Name:                   "Unrecovered ECC Error",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
	141: {
		ID:                     141,
		Name:                   "Reserved",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	142: {
		ID:                     142,
		Name:                   "Unrecovered ECC Error",
		Description:            "",
		HWError:                false,
		DriverError:            false,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           false,
	},
	143: {
		ID:                     143,
		Name:                   "GPU Initialization Failure",
		Description:            "",
		HWError:                true,
		DriverError:            true,
		UserAppError:           false,
		SystemMemoryCorruption: false,
		BusError:               false,
		ThermalIssue:           false,
		FBCorruption:           true,
	},
}
