// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: session.proto

package sessionv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentPacket_Hello
	//	*AgentPacket_Result
	Payload       isAgentPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPacket) Reset() {
	*x = AgentPacket{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPacket) ProtoMessage() {}

func (x *AgentPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPacket.ProtoReflect.Descriptor instead.
func (*AgentPacket) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *AgentPacket) GetPayload() isAgentPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentPacket) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentPacket_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentPacket) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*AgentPacket_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAgentPacket_Payload interface {
	isAgentPacket_Payload()
}

type AgentPacket_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentPacket_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*AgentPacket_Hello) isAgentPacket_Payload() {}

func (*AgentPacket_Result) isAgentPacket_Payload() {}

type ManagerPacket struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ManagerPacket_HelloAck
	//	*ManagerPacket_DrainNotice
	//	*ManagerPacket_GetHealthStates
	//	*ManagerPacket_GetEvents
	//	*ManagerPacket_GetMetrics
	//	*ManagerPacket_Update
	//	*ManagerPacket_SetHealthy
	//	*ManagerPacket_Reboot
	//	*ManagerPacket_UpdateConfig
	//	*ManagerPacket_Bootstrap
	//	*ManagerPacket_InjectFault
	//	*ManagerPacket_Diagnostic
	//	*ManagerPacket_GetPackageStatus
	//	*ManagerPacket_Logout
	//	*ManagerPacket_Gossip
	//	*ManagerPacket_TriggerComponent
	//	*ManagerPacket_SetPluginSpecs
	//	*ManagerPacket_UpdateToken
	//	*ManagerPacket_GetKapMtlsStatus
	//	*ManagerPacket_UpdateKapMtlsCredentials
	//	*ManagerPacket_ActivateKapMtls
	Payload       isManagerPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerPacket) Reset() {
	*x = ManagerPacket{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerPacket) ProtoMessage() {}

func (x *ManagerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerPacket.ProtoReflect.Descriptor instead.
func (*ManagerPacket) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerPacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ManagerPacket) GetPayload() isManagerPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ManagerPacket) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ManagerPacket) GetDrainNotice() *DrainNotice {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_DrainNotice); ok {
			return x.DrainNotice
		}
	}
	return nil
}

func (x *ManagerPacket) GetGetHealthStates() *GetHealthStatesRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_GetHealthStates); ok {
			return x.GetHealthStates
		}
	}
	return nil
}

func (x *ManagerPacket) GetGetEvents() *GetEventsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_GetEvents); ok {
			return x.GetEvents
		}
	}
	return nil
}

func (x *ManagerPacket) GetGetMetrics() *GetMetricsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_GetMetrics); ok {
			return x.GetMetrics
		}
	}
	return nil
}

func (x *ManagerPacket) GetUpdate() *UpdateRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *ManagerPacket) GetSetHealthy() *SetHealthyRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_SetHealthy); ok {
			return x.SetHealthy
		}
	}
	return nil
}

func (x *ManagerPacket) GetReboot() *RebootRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *ManagerPacket) GetUpdateConfig() *UpdateConfigRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_UpdateConfig); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *ManagerPacket) GetBootstrap() *BootstrapRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_Bootstrap); ok {
			return x.Bootstrap
		}
	}
	return nil
}

func (x *ManagerPacket) GetInjectFault() *InjectFaultRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_InjectFault); ok {
			return x.InjectFault
		}
	}
	return nil
}

func (x *ManagerPacket) GetDiagnostic() *DiagnosticRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_Diagnostic); ok {
			return x.Diagnostic
		}
	}
	return nil
}

func (x *ManagerPacket) GetGetPackageStatus() *GetPackageStatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_GetPackageStatus); ok {
			return x.GetPackageStatus
		}
	}
	return nil
}

func (x *ManagerPacket) GetLogout() *LogoutRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_Logout); ok {
			return x.Logout
		}
	}
	return nil
}

func (x *ManagerPacket) GetGossip() *GossipRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_Gossip); ok {
			return x.Gossip
		}
	}
	return nil
}

func (x *ManagerPacket) GetTriggerComponent() *TriggerComponentRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_TriggerComponent); ok {
			return x.TriggerComponent
		}
	}
	return nil
}

func (x *ManagerPacket) GetSetPluginSpecs() *SetPluginSpecsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_SetPluginSpecs); ok {
			return x.SetPluginSpecs
		}
	}
	return nil
}

func (x *ManagerPacket) GetUpdateToken() *UpdateTokenRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_UpdateToken); ok {
			return x.UpdateToken
		}
	}
	return nil
}

func (x *ManagerPacket) GetGetKapMtlsStatus() *GetKAPMTLSStatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_GetKapMtlsStatus); ok {
			return x.GetKapMtlsStatus
		}
	}
	return nil
}

func (x *ManagerPacket) GetUpdateKapMtlsCredentials() *UpdateKAPMTLSCredentialsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_UpdateKapMtlsCredentials); ok {
			return x.UpdateKapMtlsCredentials
		}
	}
	return nil
}

func (x *ManagerPacket) GetActivateKapMtls() *ActivateKAPMTLSRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerPacket_ActivateKapMtls); ok {
			return x.ActivateKapMtls
		}
	}
	return nil
}

type isManagerPacket_Payload interface {
	isManagerPacket_Payload()
}

type ManagerPacket_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ManagerPacket_DrainNotice struct {
	DrainNotice *DrainNotice `protobuf:"bytes,3,opt,name=drain_notice,json=drainNotice,proto3,oneof"`
}

type ManagerPacket_GetHealthStates struct {
	GetHealthStates *GetHealthStatesRequest `protobuf:"bytes,10,opt,name=get_health_states,json=getHealthStates,proto3,oneof"`
}

type ManagerPacket_GetEvents struct {
	GetEvents *GetEventsRequest `protobuf:"bytes,11,opt,name=get_events,json=getEvents,proto3,oneof"`
}

type ManagerPacket_GetMetrics struct {
	GetMetrics *GetMetricsRequest `protobuf:"bytes,12,opt,name=get_metrics,json=getMetrics,proto3,oneof"`
}

type ManagerPacket_Update struct {
	Update *UpdateRequest `protobuf:"bytes,13,opt,name=update,proto3,oneof"`
}

type ManagerPacket_SetHealthy struct {
	SetHealthy *SetHealthyRequest `protobuf:"bytes,14,opt,name=set_healthy,json=setHealthy,proto3,oneof"`
}

type ManagerPacket_Reboot struct {
	Reboot *RebootRequest `protobuf:"bytes,15,opt,name=reboot,proto3,oneof"`
}

type ManagerPacket_UpdateConfig struct {
	UpdateConfig *UpdateConfigRequest `protobuf:"bytes,16,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type ManagerPacket_Bootstrap struct {
	Bootstrap *BootstrapRequest `protobuf:"bytes,17,opt,name=bootstrap,proto3,oneof"`
}

type ManagerPacket_InjectFault struct {
	InjectFault *InjectFaultRequest `protobuf:"bytes,18,opt,name=inject_fault,json=injectFault,proto3,oneof"`
}

type ManagerPacket_Diagnostic struct {
	Diagnostic *DiagnosticRequest `protobuf:"bytes,19,opt,name=diagnostic,proto3,oneof"`
}

type ManagerPacket_GetPackageStatus struct {
	GetPackageStatus *GetPackageStatusRequest `protobuf:"bytes,20,opt,name=get_package_status,json=getPackageStatus,proto3,oneof"`
}

type ManagerPacket_Logout struct {
	Logout *LogoutRequest `protobuf:"bytes,21,opt,name=logout,proto3,oneof"`
}

type ManagerPacket_Gossip struct {
	Gossip *GossipRequest `protobuf:"bytes,22,opt,name=gossip,proto3,oneof"`
}

type ManagerPacket_TriggerComponent struct {
	TriggerComponent *TriggerComponentRequest `protobuf:"bytes,23,opt,name=trigger_component,json=triggerComponent,proto3,oneof"`
}

type ManagerPacket_SetPluginSpecs struct {
	SetPluginSpecs *SetPluginSpecsRequest `protobuf:"bytes,24,opt,name=set_plugin_specs,json=setPluginSpecs,proto3,oneof"`
}

type ManagerPacket_UpdateToken struct {
	UpdateToken *UpdateTokenRequest `protobuf:"bytes,25,opt,name=update_token,json=updateToken,proto3,oneof"`
}

type ManagerPacket_GetKapMtlsStatus struct {
	GetKapMtlsStatus *GetKAPMTLSStatusRequest `protobuf:"bytes,26,opt,name=get_kap_mtls_status,json=getKapMtlsStatus,proto3,oneof"`
}

type ManagerPacket_UpdateKapMtlsCredentials struct {
	UpdateKapMtlsCredentials *UpdateKAPMTLSCredentialsRequest `protobuf:"bytes,27,opt,name=update_kap_mtls_credentials,json=updateKapMtlsCredentials,proto3,oneof"`
}

type ManagerPacket_ActivateKapMtls struct {
	ActivateKapMtls *ActivateKAPMTLSRequest `protobuf:"bytes,28,opt,name=activate_kap_mtls,json=activateKapMtls,proto3,oneof"`
}

func (*ManagerPacket_HelloAck) isManagerPacket_Payload() {}

func (*ManagerPacket_DrainNotice) isManagerPacket_Payload() {}

func (*ManagerPacket_GetHealthStates) isManagerPacket_Payload() {}

func (*ManagerPacket_GetEvents) isManagerPacket_Payload() {}

func (*ManagerPacket_GetMetrics) isManagerPacket_Payload() {}

func (*ManagerPacket_Update) isManagerPacket_Payload() {}

func (*ManagerPacket_SetHealthy) isManagerPacket_Payload() {}

func (*ManagerPacket_Reboot) isManagerPacket_Payload() {}

func (*ManagerPacket_UpdateConfig) isManagerPacket_Payload() {}

func (*ManagerPacket_Bootstrap) isManagerPacket_Payload() {}

func (*ManagerPacket_InjectFault) isManagerPacket_Payload() {}

func (*ManagerPacket_Diagnostic) isManagerPacket_Payload() {}

func (*ManagerPacket_GetPackageStatus) isManagerPacket_Payload() {}

func (*ManagerPacket_Logout) isManagerPacket_Payload() {}

func (*ManagerPacket_Gossip) isManagerPacket_Payload() {}

func (*ManagerPacket_TriggerComponent) isManagerPacket_Payload() {}

func (*ManagerPacket_SetPluginSpecs) isManagerPacket_Payload() {}

func (*ManagerPacket_UpdateToken) isManagerPacket_Payload() {}

func (*ManagerPacket_GetKapMtlsStatus) isManagerPacket_Payload() {}

func (*ManagerPacket_UpdateKapMtlsCredentials) isManagerPacket_Payload() {}

func (*ManagerPacket_ActivateKapMtls) isManagerPacket_Payload() {}

type Hello struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MinProtocolRevision    uint32                 `protobuf:"varint,1,opt,name=min_protocol_revision,json=minProtocolRevision,proto3" json:"min_protocol_revision,omitempty"`
	MaxProtocolRevision    uint32                 `protobuf:"varint,2,opt,name=max_protocol_revision,json=maxProtocolRevision,proto3" json:"max_protocol_revision,omitempty"`
	AgentVersion           string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	MaxReceiveMessageBytes uint32                 `protobuf:"varint,4,opt,name=max_receive_message_bytes,json=maxReceiveMessageBytes,proto3" json:"max_receive_message_bytes,omitempty"`
	Capabilities           []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetMinProtocolRevision() uint32 {
	if x != nil {
		return x.MinProtocolRevision
	}
	return 0
}

func (x *Hello) GetMaxProtocolRevision() uint32 {
	if x != nil {
		return x.MaxProtocolRevision
	}
	return 0
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetMaxReceiveMessageBytes() uint32 {
	if x != nil {
		return x.MaxReceiveMessageBytes
	}
	return 0
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HelloAck struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProtocolRevision       uint32                 `protobuf:"varint,1,opt,name=protocol_revision,json=protocolRevision,proto3" json:"protocol_revision,omitempty"`
	ManagerInstanceId      string                 `protobuf:"bytes,2,opt,name=manager_instance_id,json=managerInstanceId,proto3" json:"manager_instance_id,omitempty"`
	MaxReceiveMessageBytes uint32                 `protobuf:"varint,3,opt,name=max_receive_message_bytes,json=maxReceiveMessageBytes,proto3" json:"max_receive_message_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetProtocolRevision() uint32 {
	if x != nil {
		return x.ProtocolRevision
	}
	return 0
}

func (x *HelloAck) GetManagerInstanceId() string {
	if x != nil {
		return x.ManagerInstanceId
	}
	return ""
}

func (x *HelloAck) GetMaxReceiveMessageBytes() uint32 {
	if x != nil {
		return x.MaxReceiveMessageBytes
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Result) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type GetHealthStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthStatesRequest) Reset() {
	*x = GetHealthStatesRequest{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthStatesRequest) ProtoMessage() {}

func (x *GetHealthStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthStatesRequest.ProtoReflect.Descriptor instead.
func (*GetHealthStatesRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetEventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceNanos    int64                  `protobuf:"varint,1,opt,name=since_nanos,json=sinceNanos,proto3" json:"since_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricsRequest) GetSinceNanos() int64 {
	if x != nil {
		return x.SinceNanos
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SinceNanos    int64                  `protobuf:"varint,2,opt,name=since_nanos,json=sinceNanos,proto3" json:"since_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateRequest) GetSinceNanos() int64 {
	if x != nil {
		return x.SinceNanos
	}
	return 0
}

type SetHealthyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Components    []string               `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	SinceNanos    int64                  `protobuf:"varint,2,opt,name=since_nanos,json=sinceNanos,proto3" json:"since_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHealthyRequest) Reset() {
	*x = SetHealthyRequest{}
	mi := &file_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHealthyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHealthyRequest) ProtoMessage() {}

func (x *SetHealthyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHealthyRequest.ProtoReflect.Descriptor instead.
func (*SetHealthyRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{9}
}

func (x *SetHealthyRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *SetHealthyRequest) GetSinceNanos() int64 {
	if x != nil {
		return x.SinceNanos
	}
	return 0
}

type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{10}
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateConfigRequest) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type BootstrapRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int64                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ScriptBase64   string                 `protobuf:"bytes,2,opt,name=script_base64,json=scriptBase64,proto3" json:"script_base64,omitempty"`
	RequestPresent bool                   `protobuf:"varint,3,opt,name=request_present,json=requestPresent,proto3" json:"request_present,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{12}
}

func (x *BootstrapRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *BootstrapRequest) GetScriptBase64() string {
	if x != nil {
		return x.ScriptBase64
	}
	return ""
}

func (x *BootstrapRequest) GetRequestPresent() bool {
	if x != nil {
		return x.RequestPresent
	}
	return false
}

type InjectFaultRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestPresent bool                   `protobuf:"varint,1,opt,name=request_present,json=requestPresent,proto3" json:"request_present,omitempty"`
	// Types that are valid to be assigned to Fault:
	//
	//	*InjectFaultRequest_Xid
	//	*InjectFaultRequest_KernelMessage
	Fault         isInjectFaultRequest_Fault `protobuf_oneof:"fault"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFaultRequest) Reset() {
	*x = InjectFaultRequest{}
	mi := &file_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFaultRequest) ProtoMessage() {}

func (x *InjectFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFaultRequest.ProtoReflect.Descriptor instead.
func (*InjectFaultRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{13}
}

func (x *InjectFaultRequest) GetRequestPresent() bool {
	if x != nil {
		return x.RequestPresent
	}
	return false
}

func (x *InjectFaultRequest) GetFault() isInjectFaultRequest_Fault {
	if x != nil {
		return x.Fault
	}
	return nil
}

func (x *InjectFaultRequest) GetXid() int64 {
	if x != nil {
		if x, ok := x.Fault.(*InjectFaultRequest_Xid); ok {
			return x.Xid
		}
	}
	return 0
}

func (x *InjectFaultRequest) GetKernelMessage() *KernelMessage {
	if x != nil {
		if x, ok := x.Fault.(*InjectFaultRequest_KernelMessage); ok {
			return x.KernelMessage
		}
	}
	return nil
}

type isInjectFaultRequest_Fault interface {
	isInjectFaultRequest_Fault()
}

type InjectFaultRequest_Xid struct {
	Xid int64 `protobuf:"varint,2,opt,name=xid,proto3,oneof"`
}

type InjectFaultRequest_KernelMessage struct {
	KernelMessage *KernelMessage `protobuf:"bytes,3,opt,name=kernel_message,json=kernelMessage,proto3,oneof"`
}

func (*InjectFaultRequest_Xid) isInjectFaultRequest_Fault() {}

func (*InjectFaultRequest_KernelMessage) isInjectFaultRequest_Fault() {}

type KernelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      string                 `protobuf:"bytes,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelMessage) Reset() {
	*x = KernelMessage{}
	mi := &file_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelMessage) ProtoMessage() {}

func (x *KernelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelMessage.ProtoReflect.Descriptor instead.
func (*KernelMessage) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{14}
}

func (x *KernelMessage) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *KernelMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DiagnosticRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReportId       string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RequestPresent bool                   `protobuf:"varint,4,opt,name=request_present,json=requestPresent,proto3" json:"request_present,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiagnosticRequest) Reset() {
	*x = DiagnosticRequest{}
	mi := &file_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticRequest) ProtoMessage() {}

func (x *DiagnosticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticRequest.ProtoReflect.Descriptor instead.
func (*DiagnosticRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{15}
}

func (x *DiagnosticRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *DiagnosticRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiagnosticRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DiagnosticRequest) GetRequestPresent() bool {
	if x != nil {
		return x.RequestPresent
	}
	return false
}

type GetPackageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageStatusRequest) Reset() {
	*x = GetPackageStatusRequest{}
	mi := &file_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageStatusRequest) ProtoMessage() {}

func (x *GetPackageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPackageStatusRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{16}
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{17}
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{18}
}

type TriggerComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	TagName       string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerComponentRequest) Reset() {
	*x = TriggerComponentRequest{}
	mi := &file_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerComponentRequest) ProtoMessage() {}

func (x *TriggerComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerComponentRequest.ProtoReflect.Descriptor instead.
func (*TriggerComponentRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{19}
}

func (x *TriggerComponentRequest) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *TriggerComponentRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type SetPluginSpecsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecsPresent  bool                   `protobuf:"varint,1,opt,name=specs_present,json=specsPresent,proto3" json:"specs_present,omitempty"`
	Specs         []*PluginSpec          `protobuf:"bytes,2,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPluginSpecsRequest) Reset() {
	*x = SetPluginSpecsRequest{}
	mi := &file_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPluginSpecsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPluginSpecsRequest) ProtoMessage() {}

func (x *SetPluginSpecsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPluginSpecsRequest.ProtoReflect.Descriptor instead.
func (*SetPluginSpecsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{20}
}

func (x *SetPluginSpecsRequest) GetSpecsPresent() bool {
	if x != nil {
		return x.SpecsPresent
	}
	return false
}

func (x *SetPluginSpecsRequest) GetSpecs() []*PluginSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type PluginSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PluginName        string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginType        string                 `protobuf:"bytes,2,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"`
	ComponentList     []string               `protobuf:"bytes,3,rep,name=component_list,json=componentList,proto3" json:"component_list,omitempty"`
	ComponentListFile string                 `protobuf:"bytes,4,opt,name=component_list_file,json=componentListFile,proto3" json:"component_list_file,omitempty"`
	RunMode           string                 `protobuf:"bytes,5,opt,name=run_mode,json=runMode,proto3" json:"run_mode,omitempty"`
	Tags              []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	HealthStatePlugin *Plugin                `protobuf:"bytes,7,opt,name=health_state_plugin,json=healthStatePlugin,proto3" json:"health_state_plugin,omitempty"`
	TimeoutNanos      int64                  `protobuf:"varint,8,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	IntervalNanos     int64                  `protobuf:"varint,9,opt,name=interval_nanos,json=intervalNanos,proto3" json:"interval_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginSpec) Reset() {
	*x = PluginSpec{}
	mi := &file_session_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpec) ProtoMessage() {}

func (x *PluginSpec) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpec.ProtoReflect.Descriptor instead.
func (*PluginSpec) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{21}
}

func (x *PluginSpec) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *PluginSpec) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *PluginSpec) GetComponentList() []string {
	if x != nil {
		return x.ComponentList
	}
	return nil
}

func (x *PluginSpec) GetComponentListFile() string {
	if x != nil {
		return x.ComponentListFile
	}
	return ""
}

func (x *PluginSpec) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *PluginSpec) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginSpec) GetHealthStatePlugin() *Plugin {
	if x != nil {
		return x.HealthStatePlugin
	}
	return nil
}

func (x *PluginSpec) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *PluginSpec) GetIntervalNanos() int64 {
	if x != nil {
		return x.IntervalNanos
	}
	return 0
}

type Plugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*PluginStep          `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	Parser        *PluginOutputParser    `protobuf:"bytes,2,opt,name=parser,proto3" json:"parser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_session_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{22}
}

func (x *Plugin) GetSteps() []*PluginStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Plugin) GetParser() *PluginOutputParser {
	if x != nil {
		return x.Parser
	}
	return nil
}

type PluginStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RunBashScript *BashScript            `protobuf:"bytes,2,opt,name=run_bash_script,json=runBashScript,proto3" json:"run_bash_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStep) Reset() {
	*x = PluginStep{}
	mi := &file_session_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStep) ProtoMessage() {}

func (x *PluginStep) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStep.ProtoReflect.Descriptor instead.
func (*PluginStep) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{23}
}

func (x *PluginStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginStep) GetRunBashScript() *BashScript {
	if x != nil {
		return x.RunBashScript
	}
	return nil
}

type BashScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BashScript) Reset() {
	*x = BashScript{}
	mi := &file_session_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BashScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BashScript) ProtoMessage() {}

func (x *BashScript) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BashScript.ProtoReflect.Descriptor instead.
func (*BashScript) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{24}
}

func (x *BashScript) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BashScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type PluginOutputParser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPaths     []*PluginJSONPath      `protobuf:"bytes,1,rep,name=json_paths,json=jsonPaths,proto3" json:"json_paths,omitempty"`
	LogPath       string                 `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOutputParser) Reset() {
	*x = PluginOutputParser{}
	mi := &file_session_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOutputParser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOutputParser) ProtoMessage() {}

func (x *PluginOutputParser) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOutputParser.ProtoReflect.Descriptor instead.
func (*PluginOutputParser) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{25}
}

func (x *PluginOutputParser) GetJsonPaths() []*PluginJSONPath {
	if x != nil {
		return x.JsonPaths
	}
	return nil
}

func (x *PluginOutputParser) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

type PluginJSONPath struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Query            string                      `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Field            string                      `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Expect           *PluginMatchRule            `protobuf:"bytes,3,opt,name=expect,proto3" json:"expect,omitempty"`
	SuggestedActions map[string]*PluginMatchRule `protobuf:"bytes,4,rep,name=suggested_actions,json=suggestedActions,proto3" json:"suggested_actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginJSONPath) Reset() {
	*x = PluginJSONPath{}
	mi := &file_session_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginJSONPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginJSONPath) ProtoMessage() {}

func (x *PluginJSONPath) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginJSONPath.ProtoReflect.Descriptor instead.
func (*PluginJSONPath) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{26}
}

func (x *PluginJSONPath) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PluginJSONPath) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *PluginJSONPath) GetExpect() *PluginMatchRule {
	if x != nil {
		return x.Expect
	}
	return nil
}

func (x *PluginJSONPath) GetSuggestedActions() map[string]*PluginMatchRule {
	if x != nil {
		return x.SuggestedActions
	}
	return nil
}

type PluginMatchRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regex         *string                `protobuf:"bytes,1,opt,name=regex,proto3,oneof" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMatchRule) Reset() {
	*x = PluginMatchRule{}
	mi := &file_session_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMatchRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMatchRule) ProtoMessage() {}

func (x *PluginMatchRule) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMatchRule.ProtoReflect.Descriptor instead.
func (*PluginMatchRule) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{27}
}

func (x *PluginMatchRule) GetRegex() string {
	if x != nil && x.Regex != nil {
		return *x.Regex
	}
	return ""
}

type UpdateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenRequest) Reset() {
	*x = UpdateTokenRequest{}
	mi := &file_session_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenRequest) ProtoMessage() {}

func (x *UpdateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdateTokenRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetKAPMTLSStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKAPMTLSStatusRequest) Reset() {
	*x = GetKAPMTLSStatusRequest{}
	mi := &file_session_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKAPMTLSStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKAPMTLSStatusRequest) ProtoMessage() {}

func (x *GetKAPMTLSStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKAPMTLSStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKAPMTLSStatusRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{29}
}

type UpdateKAPMTLSCredentialsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem       []byte                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	PrivateKeyPem        []byte                 `protobuf:"bytes,2,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	GatewayCaPem         []byte                 `protobuf:"bytes,3,opt,name=gateway_ca_pem,json=gatewayCaPem,proto3" json:"gateway_ca_pem,omitempty"`
	GatewayEndpoint      string                 `protobuf:"bytes,4,opt,name=gateway_endpoint,json=gatewayEndpoint,proto3" json:"gateway_endpoint,omitempty"`
	ServerName           string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ClientCaFingerprint  string                 `protobuf:"bytes,6,opt,name=client_ca_fingerprint,json=clientCaFingerprint,proto3" json:"client_ca_fingerprint,omitempty"`
	GatewayCaFingerprint string                 `protobuf:"bytes,7,opt,name=gateway_ca_fingerprint,json=gatewayCaFingerprint,proto3" json:"gateway_ca_fingerprint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateKAPMTLSCredentialsRequest) Reset() {
	*x = UpdateKAPMTLSCredentialsRequest{}
	mi := &file_session_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKAPMTLSCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKAPMTLSCredentialsRequest) ProtoMessage() {}

func (x *UpdateKAPMTLSCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKAPMTLSCredentialsRequest.ProtoReflect.Descriptor instead.
func (*UpdateKAPMTLSCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateKAPMTLSCredentialsRequest) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *UpdateKAPMTLSCredentialsRequest) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

func (x *UpdateKAPMTLSCredentialsRequest) GetGatewayCaPem() []byte {
	if x != nil {
		return x.GatewayCaPem
	}
	return nil
}

func (x *UpdateKAPMTLSCredentialsRequest) GetGatewayEndpoint() string {
	if x != nil {
		return x.GatewayEndpoint
	}
	return ""
}

func (x *UpdateKAPMTLSCredentialsRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *UpdateKAPMTLSCredentialsRequest) GetClientCaFingerprint() string {
	if x != nil {
		return x.ClientCaFingerprint
	}
	return ""
}

func (x *UpdateKAPMTLSCredentialsRequest) GetGatewayCaFingerprint() string {
	if x != nil {
		return x.GatewayCaFingerprint
	}
	return ""
}

type ActivateKAPMTLSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateKAPMTLSRequest) Reset() {
	*x = ActivateKAPMTLSRequest{}
	mi := &file_session_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKAPMTLSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKAPMTLSRequest) ProtoMessage() {}

func (x *ActivateKAPMTLSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKAPMTLSRequest.ProtoReflect.Descriptor instead.
func (*ActivateKAPMTLSRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{31}
}

type DrainNotice struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReconnectAfterMillis int64                  `protobuf:"varint,1,opt,name=reconnect_after_millis,json=reconnectAfterMillis,proto3" json:"reconnect_after_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DrainNotice) Reset() {
	*x = DrainNotice{}
	mi := &file_session_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNotice) ProtoMessage() {}

func (x *DrainNotice) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNotice.ProtoReflect.Descriptor instead.
func (*DrainNotice) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{32}
}

func (x *DrainNotice) GetReconnectAfterMillis() int64 {
	if x != nil {
		return x.ReconnectAfterMillis
	}
	return 0
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\x0fgpud.session.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n" +
	"\vAgentPacket\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.gpud.session.v2.HelloH\x00R\x05hello\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x17.gpud.session.v2.ResultH\x00R\x06resultB\t\n" +
	"\apayload\"\xe3\f\n" +
	"\rManagerPacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x128\n" +
	"\thello_ack\x18\x01 \x01(\v2\x19.gpud.session.v2.HelloAckH\x00R\bhelloAck\x12A\n" +
	"\fdrain_notice\x18\x03 \x01(\v2\x1c.gpud.session.v2.DrainNoticeH\x00R\vdrainNotice\x12U\n" +
	"\x11get_health_states\x18\n" +
	" \x01(\v2'.gpud.session.v2.GetHealthStatesRequestH\x00R\x0fgetHealthStates\x12B\n" +
	"\n" +
	"get_events\x18\v \x01(\v2!.gpud.session.v2.GetEventsRequestH\x00R\tgetEvents\x12E\n" +
	"\vget_metrics\x18\f \x01(\v2\".gpud.session.v2.GetMetricsRequestH\x00R\n" +
	"getMetrics\x128\n" +
	"\x06update\x18\r \x01(\v2\x1e.gpud.session.v2.UpdateRequestH\x00R\x06update\x12E\n" +
	"\vset_healthy\x18\x0e \x01(\v2\".gpud.session.v2.SetHealthyRequestH\x00R\n" +
	"setHealthy\x128\n" +
	"\x06reboot\x18\x0f \x01(\v2\x1e.gpud.session.v2.RebootRequestH\x00R\x06reboot\x12K\n" +
	"\rupdate_config\x18\x10 \x01(\v2$.gpud.session.v2.UpdateConfigRequestH\x00R\fupdateConfig\x12A\n" +
	"\tbootstrap\x18\x11 \x01(\v2!.gpud.session.v2.BootstrapRequestH\x00R\tbootstrap\x12H\n" +
	"\finject_fault\x18\x12 \x01(\v2#.gpud.session.v2.InjectFaultRequestH\x00R\vinjectFault\x12D\n" +
	"\n" +
	"diagnostic\x18\x13 \x01(\v2\".gpud.session.v2.DiagnosticRequestH\x00R\n" +
	"diagnostic\x12X\n" +
	"\x12get_package_status\x18\x14 \x01(\v2(.gpud.session.v2.GetPackageStatusRequestH\x00R\x10getPackageStatus\x128\n" +
	"\x06logout\x18\x15 \x01(\v2\x1e.gpud.session.v2.LogoutRequestH\x00R\x06logout\x128\n" +
	"\x06gossip\x18\x16 \x01(\v2\x1e.gpud.session.v2.GossipRequestH\x00R\x06gossip\x12W\n" +
	"\x11trigger_component\x18\x17 \x01(\v2(.gpud.session.v2.TriggerComponentRequestH\x00R\x10triggerComponent\x12R\n" +
	"\x10set_plugin_specs\x18\x18 \x01(\v2&.gpud.session.v2.SetPluginSpecsRequestH\x00R\x0esetPluginSpecs\x12H\n" +
	"\fupdate_token\x18\x19 \x01(\v2#.gpud.session.v2.UpdateTokenRequestH\x00R\vupdateToken\x12Y\n" +
	"\x13get_kap_mtls_status\x18\x1a \x01(\v2(.gpud.session.v2.GetKAPMTLSStatusRequestH\x00R\x10getKapMtlsStatus\x12q\n" +
	"\x1bupdate_kap_mtls_credentials\x18\x1b \x01(\v20.gpud.session.v2.UpdateKAPMTLSCredentialsRequestH\x00R\x18updateKapMtlsCredentials\x12U\n" +
	"\x11activate_kap_mtls\x18\x1c \x01(\v2'.gpud.session.v2.ActivateKAPMTLSRequestH\x00R\x0factivateKapMtlsB\t\n" +
	"\apayloadJ\x04\b\x02\x10\x03\"\xf3\x01\n" +
	"\x05Hello\x122\n" +
	"\x15min_protocol_revision\x18\x01 \x01(\rR\x13minProtocolRevision\x122\n" +
	"\x15max_protocol_revision\x18\x02 \x01(\rR\x13maxProtocolRevision\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x129\n" +
	"\x19max_receive_message_bytes\x18\x04 \x01(\rR\x16maxReceiveMessageBytes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xa2\x01\n" +
	"\bHelloAck\x12+\n" +
	"\x11protocol_revision\x18\x01 \x01(\rR\x10protocolRevision\x12.\n" +
	"\x13manager_instance_id\x18\x02 \x01(\tR\x11managerInstanceId\x129\n" +
	"\x19max_receive_message_bytes\x18\x03 \x01(\rR\x16maxReceiveMessageBytes\"J\n" +
	"\x06Result\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"\x18\n" +
	"\x16GetHealthStatesRequest\"\x84\x01\n" +
	"\x10GetEventsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"4\n" +
	"\x11GetMetricsRequest\x12\x1f\n" +
	"\vsince_nanos\x18\x01 \x01(\x03R\n" +
	"sinceNanos\"J\n" +
	"\rUpdateRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vsince_nanos\x18\x02 \x01(\x03R\n" +
	"sinceNanos\"T\n" +
	"\x11SetHealthyRequest\x12\x1e\n" +
	"\n" +
	"components\x18\x01 \x03(\tR\n" +
	"components\x12\x1f\n" +
	"\vsince_nanos\x18\x02 \x01(\x03R\n" +
	"sinceNanos\"\x0f\n" +
	"\rRebootRequest\"\x9a\x01\n" +
	"\x13UpdateConfigRequest\x12H\n" +
	"\x06values\x18\x01 \x03(\v20.gpud.session.v2.UpdateConfigRequest.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x10BootstrapRequest\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x03R\x0etimeoutSeconds\x12#\n" +
	"\rscript_base64\x18\x02 \x01(\tR\fscriptBase64\x12'\n" +
	"\x0frequest_present\x18\x03 \x01(\bR\x0erequestPresent\"\xa3\x01\n" +
	"\x12InjectFaultRequest\x12'\n" +
	"\x0frequest_present\x18\x01 \x01(\bR\x0erequestPresent\x12\x12\n" +
	"\x03xid\x18\x02 \x01(\x03H\x00R\x03xid\x12G\n" +
	"\x0ekernel_message\x18\x03 \x01(\v2\x1e.gpud.session.v2.KernelMessageH\x00R\rkernelMessageB\a\n" +
	"\x05fault\"E\n" +
	"\rKernelMessage\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\tR\bpriority\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x01\n" +
	"\x11DiagnosticRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\x12'\n" +
	"\x0frequest_present\x18\x04 \x01(\bR\x0erequestPresent\"\x19\n" +
	"\x17GetPackageStatusRequest\"\x0f\n" +
	"\rLogoutRequest\"\x0f\n" +
	"\rGossipRequest\"[\n" +
	"\x17TriggerComponentRequest\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\"o\n" +
	"\x15SetPluginSpecsRequest\x12#\n" +
	"\rspecs_present\x18\x01 \x01(\bR\fspecsPresent\x121\n" +
	"\x05specs\x18\x02 \x03(\v2\x1b.gpud.session.v2.PluginSpecR\x05specs\"\xe9\x02\n" +
	"\n" +
	"PluginSpec\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1f\n" +
	"\vplugin_type\x18\x02 \x01(\tR\n" +
	"pluginType\x12%\n" +
	"\x0ecomponent_list\x18\x03 \x03(\tR\rcomponentList\x12.\n" +
	"\x13component_list_file\x18\x04 \x01(\tR\x11componentListFile\x12\x19\n" +
	"\brun_mode\x18\x05 \x01(\tR\arunMode\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12G\n" +
	"\x13health_state_plugin\x18\a \x01(\v2\x17.gpud.session.v2.PluginR\x11healthStatePlugin\x12#\n" +
	"\rtimeout_nanos\x18\b \x01(\x03R\ftimeoutNanos\x12%\n" +
	"\x0einterval_nanos\x18\t \x01(\x03R\rintervalNanos\"x\n" +
	"\x06Plugin\x121\n" +
	"\x05steps\x18\x01 \x03(\v2\x1b.gpud.session.v2.PluginStepR\x05steps\x12;\n" +
	"\x06parser\x18\x02 \x01(\v2#.gpud.session.v2.PluginOutputParserR\x06parser\"e\n" +
	"\n" +
	"PluginStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\x0frun_bash_script\x18\x02 \x01(\v2\x1b.gpud.session.v2.BashScriptR\rrunBashScript\"G\n" +
	"\n" +
	"BashScript\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\"o\n" +
	"\x12PluginOutputParser\x12>\n" +
	"\n" +
	"json_paths\x18\x01 \x03(\v2\x1f.gpud.session.v2.PluginJSONPathR\tjsonPaths\x12\x19\n" +
	"\blog_path\x18\x02 \x01(\tR\alogPath\"\xc1\x02\n" +
	"\x0ePluginJSONPath\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x128\n" +
	"\x06expect\x18\x03 \x01(\v2 .gpud.session.v2.PluginMatchRuleR\x06expect\x12b\n" +
	"\x11suggested_actions\x18\x04 \x03(\v25.gpud.session.v2.PluginJSONPath.SuggestedActionsEntryR\x10suggestedActions\x1ae\n" +
	"\x15SuggestedActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .gpud.session.v2.PluginMatchRuleR\x05value:\x028\x01\"6\n" +
	"\x0fPluginMatchRule\x12\x19\n" +
	"\x05regex\x18\x01 \x01(\tH\x00R\x05regex\x88\x01\x01B\b\n" +
	"\x06_regex\"*\n" +
	"\x12UpdateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x19\n" +
	"\x17GetKAPMTLSStatusRequest\"\xce\x02\n" +
	"\x1fUpdateKAPMTLSCredentialsRequest\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12&\n" +
	"\x0fprivate_key_pem\x18\x02 \x01(\fR\rprivateKeyPem\x12$\n" +
	"\x0egateway_ca_pem\x18\x03 \x01(\fR\fgatewayCaPem\x12)\n" +
	"\x10gateway_endpoint\x18\x04 \x01(\tR\x0fgatewayEndpoint\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x122\n" +
	"\x15client_ca_fingerprint\x18\x06 \x01(\tR\x13clientCaFingerprint\x124\n" +
	"\x16gateway_ca_fingerprint\x18\a \x01(\tR\x14gatewayCaFingerprint\"\x18\n" +
	"\x16ActivateKAPMTLSRequest\"C\n" +
	"\vDrainNotice\x124\n" +
	"\x16reconnect_after_millis\x18\x01 \x01(\x03R\x14reconnectAfterMillis2]\n" +
	"\x0eSessionService\x12K\n" +
	"\aConnect\x12\x1c.gpud.session.v2.AgentPacket\x1a\x1e.gpud.session.v2.ManagerPacket(\x010\x01B3Z1github.com/leptonai/gpud/pkg/session/v2;sessionv2b\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_session_proto_goTypes = []any{
	(*AgentPacket)(nil),                     // 0: gpud.session.v2.AgentPacket
	(*ManagerPacket)(nil),                   // 1: gpud.session.v2.ManagerPacket
	(*Hello)(nil),                           // 2: gpud.session.v2.Hello
	(*HelloAck)(nil),                        // 3: gpud.session.v2.HelloAck
	(*Result)(nil),                          // 4: gpud.session.v2.Result
	(*GetHealthStatesRequest)(nil),          // 5: gpud.session.v2.GetHealthStatesRequest
	(*GetEventsRequest)(nil),                // 6: gpud.session.v2.GetEventsRequest
	(*GetMetricsRequest)(nil),               // 7: gpud.session.v2.GetMetricsRequest
	(*UpdateRequest)(nil),                   // 8: gpud.session.v2.UpdateRequest
	(*SetHealthyRequest)(nil),               // 9: gpud.session.v2.SetHealthyRequest
	(*RebootRequest)(nil),                   // 10: gpud.session.v2.RebootRequest
	(*UpdateConfigRequest)(nil),             // 11: gpud.session.v2.UpdateConfigRequest
	(*BootstrapRequest)(nil),                // 12: gpud.session.v2.BootstrapRequest
	(*InjectFaultRequest)(nil),              // 13: gpud.session.v2.InjectFaultRequest
	(*KernelMessage)(nil),                   // 14: gpud.session.v2.KernelMessage
	(*DiagnosticRequest)(nil),               // 15: gpud.session.v2.DiagnosticRequest
	(*GetPackageStatusRequest)(nil),         // 16: gpud.session.v2.GetPackageStatusRequest
	(*LogoutRequest)(nil),                   // 17: gpud.session.v2.LogoutRequest
	(*GossipRequest)(nil),                   // 18: gpud.session.v2.GossipRequest
	(*TriggerComponentRequest)(nil),         // 19: gpud.session.v2.TriggerComponentRequest
	(*SetPluginSpecsRequest)(nil),           // 20: gpud.session.v2.SetPluginSpecsRequest
	(*PluginSpec)(nil),                      // 21: gpud.session.v2.PluginSpec
	(*Plugin)(nil),                          // 22: gpud.session.v2.Plugin
	(*PluginStep)(nil),                      // 23: gpud.session.v2.PluginStep
	(*BashScript)(nil),                      // 24: gpud.session.v2.BashScript
	(*PluginOutputParser)(nil),              // 25: gpud.session.v2.PluginOutputParser
	(*PluginJSONPath)(nil),                  // 26: gpud.session.v2.PluginJSONPath
	(*PluginMatchRule)(nil),                 // 27: gpud.session.v2.PluginMatchRule
	(*UpdateTokenRequest)(nil),              // 28: gpud.session.v2.UpdateTokenRequest
	(*GetKAPMTLSStatusRequest)(nil),         // 29: gpud.session.v2.GetKAPMTLSStatusRequest
	(*UpdateKAPMTLSCredentialsRequest)(nil), // 30: gpud.session.v2.UpdateKAPMTLSCredentialsRequest
	(*ActivateKAPMTLSRequest)(nil),          // 31: gpud.session.v2.ActivateKAPMTLSRequest
	(*DrainNotice)(nil),                     // 32: gpud.session.v2.DrainNotice
	nil,                                     // 33: gpud.session.v2.UpdateConfigRequest.ValuesEntry
	nil,                                     // 34: gpud.session.v2.PluginJSONPath.SuggestedActionsEntry
	(*timestamppb.Timestamp)(nil),           // 35: google.protobuf.Timestamp
}
var file_session_proto_depIdxs = []int32{
	2,  // 0: gpud.session.v2.AgentPacket.hello:type_name -> gpud.session.v2.Hello
	4,  // 1: gpud.session.v2.AgentPacket.result:type_name -> gpud.session.v2.Result
	3,  // 2: gpud.session.v2.ManagerPacket.hello_ack:type_name -> gpud.session.v2.HelloAck
	32, // 3: gpud.session.v2.ManagerPacket.drain_notice:type_name -> gpud.session.v2.DrainNotice
	5,  // 4: gpud.session.v2.ManagerPacket.get_health_states:type_name -> gpud.session.v2.GetHealthStatesRequest
	6,  // 5: gpud.session.v2.ManagerPacket.get_events:type_name -> gpud.session.v2.GetEventsRequest
	7,  // 6: gpud.session.v2.ManagerPacket.get_metrics:type_name -> gpud.session.v2.GetMetricsRequest
	8,  // 7: gpud.session.v2.ManagerPacket.update:type_name -> gpud.session.v2.UpdateRequest
	9,  // 8: gpud.session.v2.ManagerPacket.set_healthy:type_name -> gpud.session.v2.SetHealthyRequest
	10, // 9: gpud.session.v2.ManagerPacket.reboot:type_name -> gpud.session.v2.RebootRequest
	11, // 10: gpud.session.v2.ManagerPacket.update_config:type_name -> gpud.session.v2.UpdateConfigRequest
	12, // 11: gpud.session.v2.ManagerPacket.bootstrap:type_name -> gpud.session.v2.BootstrapRequest
	13, // 12: gpud.session.v2.ManagerPacket.inject_fault:type_name -> gpud.session.v2.InjectFaultRequest
	15, // 13: gpud.session.v2.ManagerPacket.diagnostic:type_name -> gpud.session.v2.DiagnosticRequest
	16, // 14: gpud.session.v2.ManagerPacket.get_package_status:type_name -> gpud.session.v2.GetPackageStatusRequest
	17, // 15: gpud.session.v2.ManagerPacket.logout:type_name -> gpud.session.v2.LogoutRequest
	18, // 16: gpud.session.v2.ManagerPacket.gossip:type_name -> gpud.session.v2.GossipRequest
	19, // 17: gpud.session.v2.ManagerPacket.trigger_component:type_name -> gpud.session.v2.TriggerComponentRequest
	20, // 18: gpud.session.v2.ManagerPacket.set_plugin_specs:type_name -> gpud.session.v2.SetPluginSpecsRequest
	28, // 19: gpud.session.v2.ManagerPacket.update_token:type_name -> gpud.session.v2.UpdateTokenRequest
	29, // 20: gpud.session.v2.ManagerPacket.get_kap_mtls_status:type_name -> gpud.session.v2.GetKAPMTLSStatusRequest
	30, // 21: gpud.session.v2.ManagerPacket.update_kap_mtls_credentials:type_name -> gpud.session.v2.UpdateKAPMTLSCredentialsRequest
	31, // 22: gpud.session.v2.ManagerPacket.activate_kap_mtls:type_name -> gpud.session.v2.ActivateKAPMTLSRequest
	35, // 23: gpud.session.v2.GetEventsRequest.start_time:type_name -> google.protobuf.Timestamp
	35, // 24: gpud.session.v2.GetEventsRequest.end_time:type_name -> google.protobuf.Timestamp
	33, // 25: gpud.session.v2.UpdateConfigRequest.values:type_name -> gpud.session.v2.UpdateConfigRequest.ValuesEntry
	14, // 26: gpud.session.v2.InjectFaultRequest.kernel_message:type_name -> gpud.session.v2.KernelMessage
	21, // 27: gpud.session.v2.SetPluginSpecsRequest.specs:type_name -> gpud.session.v2.PluginSpec
	22, // 28: gpud.session.v2.PluginSpec.health_state_plugin:type_name -> gpud.session.v2.Plugin
	23, // 29: gpud.session.v2.Plugin.steps:type_name -> gpud.session.v2.PluginStep
	25, // 30: gpud.session.v2.Plugin.parser:type_name -> gpud.session.v2.PluginOutputParser
	24, // 31: gpud.session.v2.PluginStep.run_bash_script:type_name -> gpud.session.v2.BashScript
	26, // 32: gpud.session.v2.PluginOutputParser.json_paths:type_name -> gpud.session.v2.PluginJSONPath
	27, // 33: gpud.session.v2.PluginJSONPath.expect:type_name -> gpud.session.v2.PluginMatchRule
	34, // 34: gpud.session.v2.PluginJSONPath.suggested_actions:type_name -> gpud.session.v2.PluginJSONPath.SuggestedActionsEntry
	27, // 35: gpud.session.v2.PluginJSONPath.SuggestedActionsEntry.value:type_name -> gpud.session.v2.PluginMatchRule
	0,  // 36: gpud.session.v2.SessionService.Connect:input_type -> gpud.session.v2.AgentPacket
	1,  // 37: gpud.session.v2.SessionService.Connect:output_type -> gpud.session.v2.ManagerPacket
	37, // [37:38] is the sub-list for method output_type
	36, // [36:37] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_session_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentPacket_Hello)(nil),
		(*AgentPacket_Result)(nil),
	}
	file_session_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerPacket_HelloAck)(nil),
		(*ManagerPacket_DrainNotice)(nil),
		(*ManagerPacket_GetHealthStates)(nil),
		(*ManagerPacket_GetEvents)(nil),
		(*ManagerPacket_GetMetrics)(nil),
		(*ManagerPacket_Update)(nil),
		(*ManagerPacket_SetHealthy)(nil),
		(*ManagerPacket_Reboot)(nil),
		(*ManagerPacket_UpdateConfig)(nil),
		(*ManagerPacket_Bootstrap)(nil),
		(*ManagerPacket_InjectFault)(nil),
		(*ManagerPacket_Diagnostic)(nil),
		(*ManagerPacket_GetPackageStatus)(nil),
		(*ManagerPacket_Logout)(nil),
		(*ManagerPacket_Gossip)(nil),
		(*ManagerPacket_TriggerComponent)(nil),
		(*ManagerPacket_SetPluginSpecs)(nil),
		(*ManagerPacket_UpdateToken)(nil),
		(*ManagerPacket_GetKapMtlsStatus)(nil),
		(*ManagerPacket_UpdateKapMtlsCredentials)(nil),
		(*ManagerPacket_ActivateKapMtls)(nil),
	}
	file_session_proto_msgTypes[13].OneofWrappers = []any{
		(*InjectFaultRequest_Xid)(nil),
		(*InjectFaultRequest_KernelMessage)(nil),
	}
	file_session_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
