// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: session.proto

package sessionv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEnvelope_Hello
	//	*AgentEnvelope_CommandResult
	//	*AgentEnvelope_Heartbeat
	Payload       isAgentEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnvelope) Reset() {
	*x = AgentEnvelope{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnvelope) ProtoMessage() {}

func (x *AgentEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnvelope.ProtoReflect.Descriptor instead.
func (*AgentEnvelope) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEnvelope) GetPayload() isAgentEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEnvelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentEnvelope) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *AgentEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentEnvelope_Payload interface {
	isAgentEnvelope_Payload()
}

type AgentEnvelope_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentEnvelope_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,2,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type AgentEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentEnvelope_Hello) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_CommandResult) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_Heartbeat) isAgentEnvelope_Payload() {}

type ManagerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ManagerEnvelope_HelloAck
	//	*ManagerEnvelope_Command
	//	*ManagerEnvelope_HeartbeatAck
	//	*ManagerEnvelope_DrainNotice
	Payload       isManagerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerEnvelope) Reset() {
	*x = ManagerEnvelope{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEnvelope) ProtoMessage() {}

func (x *ManagerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEnvelope.ProtoReflect.Descriptor instead.
func (*ManagerEnvelope) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerEnvelope) GetPayload() isManagerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ManagerEnvelope) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ManagerEnvelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ManagerEnvelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ManagerEnvelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ManagerEnvelope) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ManagerEnvelope_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ManagerEnvelope) GetDrainNotice() *DrainNotice {
	if x != nil {
		if x, ok := x.Payload.(*ManagerEnvelope_DrainNotice); ok {
			return x.DrainNotice
		}
	}
	return nil
}

type isManagerEnvelope_Payload interface {
	isManagerEnvelope_Payload()
}

type ManagerEnvelope_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ManagerEnvelope_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type ManagerEnvelope_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,3,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ManagerEnvelope_DrainNotice struct {
	DrainNotice *DrainNotice `protobuf:"bytes,4,opt,name=drain_notice,json=drainNotice,proto3,oneof"`
}

func (*ManagerEnvelope_HelloAck) isManagerEnvelope_Payload() {}

func (*ManagerEnvelope_Command) isManagerEnvelope_Payload() {}

func (*ManagerEnvelope_HeartbeatAck) isManagerEnvelope_Payload() {}

func (*ManagerEnvelope_DrainNotice) isManagerEnvelope_Payload() {}

type Hello struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MinProtocolRevision    uint32                 `protobuf:"varint,1,opt,name=min_protocol_revision,json=minProtocolRevision,proto3" json:"min_protocol_revision,omitempty"`
	MaxProtocolRevision    uint32                 `protobuf:"varint,2,opt,name=max_protocol_revision,json=maxProtocolRevision,proto3" json:"max_protocol_revision,omitempty"`
	AgentVersion           string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	MaxReceiveMessageBytes uint32                 `protobuf:"varint,4,opt,name=max_receive_message_bytes,json=maxReceiveMessageBytes,proto3" json:"max_receive_message_bytes,omitempty"`
	Capabilities           []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetMinProtocolRevision() uint32 {
	if x != nil {
		return x.MinProtocolRevision
	}
	return 0
}

func (x *Hello) GetMaxProtocolRevision() uint32 {
	if x != nil {
		return x.MaxProtocolRevision
	}
	return 0
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetMaxReceiveMessageBytes() uint32 {
	if x != nil {
		return x.MaxReceiveMessageBytes
	}
	return 0
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HelloAck struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ProtocolRevision         uint32                 `protobuf:"varint,1,opt,name=protocol_revision,json=protocolRevision,proto3" json:"protocol_revision,omitempty"`
	ManagerInstanceId        string                 `protobuf:"bytes,2,opt,name=manager_instance_id,json=managerInstanceId,proto3" json:"manager_instance_id,omitempty"`
	MaxReceiveMessageBytes   uint32                 `protobuf:"varint,3,opt,name=max_receive_message_bytes,json=maxReceiveMessageBytes,proto3" json:"max_receive_message_bytes,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetProtocolRevision() uint32 {
	if x != nil {
		return x.ProtocolRevision
	}
	return 0
}

func (x *HelloAck) GetManagerInstanceId() string {
	if x != nil {
		return x.ManagerInstanceId
	}
	return ""
}

func (x *HelloAck) GetMaxReceiveMessageBytes() uint32 {
	if x != nil {
		return x.MaxReceiveMessageBytes
	}
	return 0
}

func (x *HelloAck) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	TimeoutMillis int64                  `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Command) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *Command) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResult) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type DrainNotice struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReconnectAfterMillis int64                  `protobuf:"varint,1,opt,name=reconnect_after_millis,json=reconnectAfterMillis,proto3" json:"reconnect_after_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DrainNotice) Reset() {
	*x = DrainNotice{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNotice) ProtoMessage() {}

func (x *DrainNotice) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNotice.ProtoReflect.Descriptor instead.
func (*DrainNotice) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

func (x *DrainNotice) GetReconnectAfterMillis() int64 {
	if x != nil {
		return x.ReconnectAfterMillis
	}
	return 0
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\x0fgpud.session.v2\"\xcf\x01\n" +
	"\rAgentEnvelope\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.gpud.session.v2.HelloH\x00R\x05hello\x12G\n" +
	"\x0ecommand_result\x18\x02 \x01(\v2\x1e.gpud.session.v2.CommandResultH\x00R\rcommandResult\x12:\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1a.gpud.session.v2.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x95\x02\n" +
	"\x0fManagerEnvelope\x128\n" +
	"\thello_ack\x18\x01 \x01(\v2\x19.gpud.session.v2.HelloAckH\x00R\bhelloAck\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x18.gpud.session.v2.CommandH\x00R\acommand\x12D\n" +
	"\rheartbeat_ack\x18\x03 \x01(\v2\x1d.gpud.session.v2.HeartbeatAckH\x00R\fheartbeatAck\x12A\n" +
	"\fdrain_notice\x18\x04 \x01(\v2\x1c.gpud.session.v2.DrainNoticeH\x00R\vdrainNoticeB\t\n" +
	"\apayload\"\xf3\x01\n" +
	"\x05Hello\x122\n" +
	"\x15min_protocol_revision\x18\x01 \x01(\rR\x13minProtocolRevision\x122\n" +
	"\x15max_protocol_revision\x18\x02 \x01(\rR\x13maxProtocolRevision\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x129\n" +
	"\x19max_receive_message_bytes\x18\x04 \x01(\rR\x16maxReceiveMessageBytes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xe0\x01\n" +
	"\bHelloAck\x12+\n" +
	"\x11protocol_revision\x18\x01 \x01(\rR\x10protocolRevision\x12.\n" +
	"\x13manager_instance_id\x18\x02 \x01(\tR\x11managerInstanceId\x129\n" +
	"\x19max_receive_message_bytes\x18\x03 \x01(\rR\x16maxReceiveMessageBytes\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\rR\x18heartbeatIntervalSeconds\"r\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\x12%\n" +
	"\x0etimeout_millis\x18\x03 \x01(\x03R\rtimeoutMillis\"Q\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"'\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"*\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"C\n" +
	"\vDrainNotice\x124\n" +
	"\x16reconnect_after_millis\x18\x01 \x01(\x03R\x14reconnectAfterMillis2a\n" +
	"\x0eSessionService\x12O\n" +
	"\aConnect\x12\x1e.gpud.session.v2.AgentEnvelope\x1a .gpud.session.v2.ManagerEnvelope(\x010\x01B3Z1github.com/leptonai/gpud/pkg/session/v2;sessionv2b\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_session_proto_goTypes = []any{
	(*AgentEnvelope)(nil),   // 0: gpud.session.v2.AgentEnvelope
	(*ManagerEnvelope)(nil), // 1: gpud.session.v2.ManagerEnvelope
	(*Hello)(nil),           // 2: gpud.session.v2.Hello
	(*HelloAck)(nil),        // 3: gpud.session.v2.HelloAck
	(*Command)(nil),         // 4: gpud.session.v2.Command
	(*CommandResult)(nil),   // 5: gpud.session.v2.CommandResult
	(*Heartbeat)(nil),       // 6: gpud.session.v2.Heartbeat
	(*HeartbeatAck)(nil),    // 7: gpud.session.v2.HeartbeatAck
	(*DrainNotice)(nil),     // 8: gpud.session.v2.DrainNotice
}
var file_session_proto_depIdxs = []int32{
	2, // 0: gpud.session.v2.AgentEnvelope.hello:type_name -> gpud.session.v2.Hello
	5, // 1: gpud.session.v2.AgentEnvelope.command_result:type_name -> gpud.session.v2.CommandResult
	6, // 2: gpud.session.v2.AgentEnvelope.heartbeat:type_name -> gpud.session.v2.Heartbeat
	3, // 3: gpud.session.v2.ManagerEnvelope.hello_ack:type_name -> gpud.session.v2.HelloAck
	4, // 4: gpud.session.v2.ManagerEnvelope.command:type_name -> gpud.session.v2.Command
	7, // 5: gpud.session.v2.ManagerEnvelope.heartbeat_ack:type_name -> gpud.session.v2.HeartbeatAck
	8, // 6: gpud.session.v2.ManagerEnvelope.drain_notice:type_name -> gpud.session.v2.DrainNotice
	0, // 7: gpud.session.v2.SessionService.Connect:input_type -> gpud.session.v2.AgentEnvelope
	1, // 8: gpud.session.v2.SessionService.Connect:output_type -> gpud.session.v2.ManagerEnvelope
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_session_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEnvelope_Hello)(nil),
		(*AgentEnvelope_CommandResult)(nil),
		(*AgentEnvelope_Heartbeat)(nil),
	}
	file_session_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerEnvelope_HelloAck)(nil),
		(*ManagerEnvelope_Command)(nil),
		(*ManagerEnvelope_HeartbeatAck)(nil),
		(*ManagerEnvelope_DrainNotice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
