name: Build and Store gpud binary

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # https://launchpad.net/ubuntu/+source/linux-aws-5.15
        # https://launchpad.net/ubuntu/+source/linux-aws-6.8
        kernel_version: [ "5.15.0-1075-aws", "6.8.0-1021-aws" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-headers-${{ matrix.kernel_version }}

      - name: Build project
        run: |
          make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpud-${{ matrix.kernel_version }}
          path: bin/gpud