name: Build and Store gpud binary

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-headers-$(uname -r)

      - name: Build project
        run: |
          make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpud
          path: bin/gpud