name: CI and Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false 
        go-version-file: go.mod 

    - name: Run tests with coverage
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        go test -coverprofile=coverage.txt
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}