name: CI and Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Run tests with coverage
      run: |
        ./scripts/tests-unit.sh
