# https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#options
name: tests-e2e

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["**"]

permissions:
  contents: read
  pull-requests: read

jobs:
  tests-e2e:
    name: tests-e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - name: run e2e tests
        run: |
          KMSG_FILE_PATH=/dev/null ./scripts/tests-e2e.sh
      - name: run e2e tests (experimental)
        run: |
          ENABLE_EXPERIMENTAL_FEATURES=true KMSG_FILE_PATH=/dev/null ./scripts/tests-e2e.sh
