# https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#options
name: tests-unit

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["**"]

permissions:
  contents: read
  pull-requests: read

jobs:
  tests-unit:
    name: tests-unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - name: run unit tests
        run: |
          KMSG_FILE_PATH=/dev/null ./scripts/tests-unit.sh
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
